server:
  port: 8080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${sky.datasource.driver-class-name}
      url: jdbc:mysql://${sky.datasource.host}:${sky.datasource.port}/${sky.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${sky.datasource.username}
      password: ${sky.datasource.password}
  redis:
    host: ${sky.redis.host}
    port: ${sky.redis.port}
    #數據庫編號(redis默認就有16個數據庫,不同數據庫中的數據完全隔離)
    database: ${sky.redis.database}

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    #設置用戶的加密密鑰,jwt過期時間和令牌
    user-secret-key: itcast
    user-ttl: 7200000
    user-token-name: authentication

    # 這裡是說要配置阿里雲,沒有,就暫時空著,以後用其他服務器進行配置也是一樣的,這只是個練習,知道怎麼回事就行
    # 這裡的字段都是自定義的,其配置屬性類在 sky-common/src/main/java/com/sky/properties/AliOssProperties.java
    # 使用的是引用項,這樣可以不用改配置文件
    # 文件上傳的工具類 sky-common/src/main/java/com/sky/utils/AliOssUtil.java
    # 文件上傳工具類初始狀態為空,所以需要一個配置類來將配置文件中的字段注入到工具類中,這個配置類在 sky-server/src/main/java/com/sky/config/AliOssConfig.java
    alioss:
      endpoint: ${sky.alioss.endpoint}
      access-key-id: ${sky.alioss.access-key-id}
      access-key-secret: ${sky.alioss.access-key-secret}
      bucket-name: ${sky.alioss.bucket-name}

  #wechat的東西,也是不存在的,僅用於佔位
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}

  #外賣商家店鋪地址(用於校驗收貨地址是否超出配送範圍)
  shop:
    address: ${sky.shop.address}
  #百度地圖開放平台的AK
  baidu:
    ak: ${sky.baidu.ak}