sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: ?Wang07735853572
  # 阿里云oss配置,這個是假的(黑馬的東西),不能用的
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tPeFLzsPPT8gG3LPW64
    access-key-secret: U6k1br0Z8ga0IXv3nxbulGTUzy6PdJ7
    bucket-name: sky-itcast
  redis:
    host: localhost
    port: 6379
    #數據庫編號(redis默認就有16個數據庫,不同數據庫中的數據完全隔離)
    database: 0

  #僅用於佔位
  wechat:
    appid:
    secret: